import type { Metadata } from "next";
import { Geist, Geist_Mono, Hanken_Grotesk } from "next/font/google";
import {AuthProvider} from "./context/AuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const prashantMono = Hanken_Grotesk({
  variable: "--font-prashant-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("https://prod.liveshare.vsengsaas.visualstudio.com/join?E93184A385155017D3FC49B60EE54E70FD73")
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${prashantMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-red-500 flex flex-col"><AuthProvider>{children}</AuthProvider></body>
    </html>
  );
}
